api_platform:
    title: Hello API Platform
    version: 1.0.0
    use_symfony_listeners: true
    defaults:
        extra_properties:
            standard_put: true
    formats:
        jsonld: ['application/ld+json']
        jsonhal: [ 'application/hal+json' ]
        json: [ 'application/json' ]
        html: [ 'text/html' ]
    swagger:
        api_keys:
            access_token:
                name: Authorization
                type: header

when@prod:
    api_platform:
        enable_docs: false
        enable_entrypoint: false
        enable_swagger: false
        enable_swagger_ui: false

    doctrine:
        keep_legacy_inflector: false