version: '3.1'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:${POSTGRES_VERSION:-11}
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      MARIADB_ROOT_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      MARIADB_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      MARIADB_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/mariadb/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
